### ISSUE TITLE
Open source checklist

### ISSUE THREAD

**Issue by lucapette** [airyhq/components#8]
- [x] Add the license
- [x] Add code of conduct 
- [ ] Improve the readme
  - [x] how to contribute section
  - [x] mention the code of conduct
  - [x] Introduce the project as part of the airy open source things (link to docs.airy.co)
- [x] github action for prettier
- [x] Add a contributing.mg file (the mono repo one can be used for the structure)

First two points can be copied as is from the mono repo
